# Generated by Django 2.0 on 2017-12-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrating',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
