# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_userbookrating_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url_l',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_m',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_s',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
